export const browserCoreExamples = [
  "aikaclaw browser status",
  "aikaclaw browser start",
  "aikaclaw browser stop",
  "aikaclaw browser tabs",
  "aikaclaw browser open https://example.com",
  "aikaclaw browser focus abcd1234",
  "aikaclaw browser close abcd1234",
  "aikaclaw browser screenshot",
  "aikaclaw browser screenshot --full-page",
  "aikaclaw browser screenshot --ref 12",
  "aikaclaw browser snapshot",
  "aikaclaw browser snapshot --format aria --limit 200",
  "aikaclaw browser snapshot --efficient",
  "aikaclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "aikaclaw browser navigate https://example.com",
  "aikaclaw browser resize 1280 720",
  "aikaclaw browser click 12 --double",
  'aikaclaw browser type 23 "hello" --submit',
  "aikaclaw browser press Enter",
  "aikaclaw browser hover 44",
  "aikaclaw browser drag 10 11",
  "aikaclaw browser select 9 OptionA OptionB",
  "aikaclaw browser upload /tmp/aikaclaw/uploads/file.pdf",
  'aikaclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "aikaclaw browser dialog --accept",
  'aikaclaw browser wait --text "Done"',
  "aikaclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "aikaclaw browser console --level error",
  "aikaclaw browser pdf",
];
